### ISSUE TITLE
Add custom data to /meta/ messages

### ISSUE THREAD

**Issue by mrpatiwi** [OlehKulykov/FayeCpp#5]
Hi, it would be awesome if to add an option to include extra data on /meta/ messages. This would be helpful to perform validations and authorization on the server side.

**Comment by OlehKulykov** [comment]
Hello, done in version 0.1.6. Added extra(ext) field to both, C++ and Objective-C, clients, use client methods **extValue()** and **setExtValue(...)**.
You can read about **ext** field here: http://docs.cometd.org/2/reference/bayeux_message_fields.html
Client logic is simple: if **ext** value **not empty** than client **will send** this value with **all messages**, othervice ignore. You can select send or not by setting/removing this value via delegate or during creation in your logic.

**Comment by mrpatiwi** [comment]
Cool! thanks!

**Comment by mrpatiwi** [comment]
I'm having a problem with getifaddrs.c while building. It says: 

-- /Pods/FayeCpp/libwebsockets/lib/getifaddrs.c:88:9: Implicit declaration of function 'lws_zalloc' is invalid in C99

**Comment by OlehKulykov** [comment]
Hello, update you podfile with next: pod 'FayeCpp', '~> 0.1.7'.
Libwebsockets had this bug, for now my patch was upplyed to theirs main branch and I make update of the submodule and provide version 0.1.7. From your side you need update your podfile.
Thank you.

**Comment by OlehKulykov** [comment]
Hello, is it fine with final update, have you any propositions? Can we close this issue?
