### ISSUE TITLE
onFayeTransportDisconnected trigger?

### ISSUE THREAD

**Issue by katopz** [OlehKulykov/FayeCpp#6]
I got `onFayeTransportDisconnected` every 30 sec and can't figure out where is that came from, 
It should be timeout I guess? Do I've to prevent this?

At present, I auto reconnect when it trigger, but I'm not sure it's best practice?

Thanks!

**Comment by OlehKulykov** [comment]
Hello, 
You have successfull connect and connection during 30 sec. This mean that you are going in a right direction. 
Sockets, in a most cases, disconnects after some time... For this purpose there is advice message with time out etc. Check this on server side implementation or locate on the client console next JSON message: ``` "advice":{"reconnect":"retry","interval":0,"timeout":45000}  ```
Detailed description you can find here: http://docs.cometd.org/reference/bayeux_message_fields.html
If received timeout bigger than 30sec (``` "timeout":30000 ```) - not as expected.

Next disconnect reason is breaking socket connection by the internet operator or even absence of the connection at all(network topology, network settings, mobile networks, unusual connection port, etc...). This happens usually than you can expect. 
So, you can make next:
1. Send ```ping message``` after some time. Thist will keeps connection alive(less than ```advice.timeout```).
2. Use sequre connection on **443** port(```wss://fayeserver:443/faye```). Prevent dropping connection by the "third factors" and, on some networks(like 3G), makes possibility esteblish initial socket connection at all.
3. Use additional faye method like ``` long-polling ```. For stable functionality on varios networks, of cource if you need be connected almost 100% of the time.

Of cource without reconnect you can't make good functionality, so keep it in mind. But, you are right, 30 sec is too small time for dropping.
Finalizing, I can tell you that all 3 methods described above I'm using in production and track which method is used.

**Comment by katopz** [comment]
@OlehKulykov Many thanks! That's crystal clear! (Wow I didn't expect this great support and response.)
Appreciated your work. You just made my day! :smile:
